import streamlit as st
import pandas as pd
import pickle
from sklearn.cluster import KMeans
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from io import BytesIO

# Loading the model
filename = "dietrec.sav"
loaded_model = pickle.load(open(filename, 'rb'))

# Reading Food.csv for diet recommendation
data = pd.read_csv("food.csv")
diet = data.drop("Food_items", axis=1)

# Applying k-means and defining the number of clusters
km = KMeans(n_clusters=4)
y_predicted = km.fit_predict(diet)

# Adding a new column containing the cluster a food item is part of
data['cluster'] = y_predicted

# Streamlit app
st.set_page_config(page_title="DIET RECOMMENDATION SYSTEM", page_icon="diet.ico")

st.title("DIET RECOMMENDATION SYSTEM")

# User input
weight = st.number_input("Enter your weight in kg", min_value=0.0, step=0.1, format="%.1f")
height = st.number_input("Enter your height in m", min_value=0.01, step=0.01, format="%.2f")  # Set a minimum height value

# Check for zero height
if height == 0:
    st.error("Error: Height should be a non-zero value.")
else:
    # Calculate BMI
    bmi = weight / (height ** 2)

    # Predict using the model
    Xdata = {'Height': [height], 'Weight': [weight], 'BMI': [bmi]}
    df = pd.DataFrame(Xdata, columns=['Height', 'Weight', 'BMI'])
    predicted = loaded_model.predict(df)
    predicted_cluster = predicted[0]

    # Display BMI and diet recommendation with styling
    st.markdown(f"### Your BMI is **{bmi:.2f}**", unsafe_allow_html=True)

    st.markdown("### Diet Recommendation:")
    recommended_food = data[data['cluster'] == predicted_cluster].Food_items.sample(21, replace=True).values

    # Create a DataFrame for day-wise schedule
    days = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
    meals = ['Breakfast', 'Lunch', 'Dinner']
    schedule = pd.DataFrame(columns=meals, index=days)

    # Populate the schedule DataFrame with recommended foods
    index = 0
    for day in days:
        for meal in meals:
            schedule.loc[day, meal] = recommended_food[index]
            index += 1

    # Display the schedule as a table
    st.table(schedule)

    # Generate PDF using ReportLab
    def generate_pdf(schedule_data):
        buffer = BytesIO()
        c = canvas.Canvas(buffer, pagesize=letter)
        c.setFont("Helvetica", 12)
        c.drawString(100, 750, "DIET RECOMMENDATION SCHEDULE")
        c.drawString(100, 730, "Generated by: WELLNESS-WAYFINDER")
        c.drawString(100, 710, "---------------------------------------------")
        y_start = 690
        for day in schedule_data.index:
            c.drawString(100, y_start, day)
            c.drawString(200, y_start, schedule_data.loc[day, 'Breakfast'])
            c.drawString(350, y_start, schedule_data.loc[day, 'Lunch'])
            c.drawString(500, y_start, schedule_data.loc[day, 'Dinner'])
            y_start -= 20
        c.save()
        buffer.seek(0)
        return buffer

    # Generate PDF and provide download button
    pdf_buffer = generate_pdf(schedule)
    st.download_button(label="Download PDF", data=pdf_buffer, file_name="diet_schedule.pdf", mime="application/pdf")
